NUMBER_OF_DIGITS_IN_PHONE_NUMBER = 3

WELCOME_MESSAGE = "Welcome to the assistant bot!"
CONTACT_ADDED = "Contact added."
CONTACT_UPDATED = "Contact updated."
EMAIL_IS_ADDED = "Email is added."

KEY_ERROR = "This name is already in the contacts."
VALUE_ERROR = "Enter the correct argument value."
INDEX_ERROR = "This contact name is absent in the address book."
PRECISE_DIGITS_ERROR = f"Phone should consist of exactly {NUMBER_OF_DIGITS_IN_PHONE_NUMBER} digits!"
INVALID_FORMAT_ERROR = "Invalid date format. Use DD.MM.YYYY"
INVALID_VALUE_ERROR = "Invalid date value. Use correct date."
INVALID_COMMAND_ERROR = "Invalid command."
EMAIL_IS_NOT_VALID = "Email is not valid."
EMAIL_IS_ALREADY_PRESENT = "Email is already present for this contact. Use 'change-email...' command"
NAME_IS_NOT_VALID = "Name is not valid."

NO_PHONE_NUMBER = "No such phone number for this contact."
CONTACT_LIST_EMPTY = "Contact list is empty."
CONTACT_IS_ALREADY_PRESENT = "There is already such a user."
PHONE_IS_IN_BOOK = "This phone number is already saved for this contact."
CONTACT_HAS_BIRTHDAY = "This contact has already their birthday"
NO_SUCH_CONTACT = "No such contact in the personal assistant."
NO_NECESSARY_TO_CONGRATULATE = "There are no letters scheduled to be mailed in the next week."
TITLE_TO_CONGRATULATE = "It's necessary to congratulate the following contacts"